### ISSUE TITLE
Docker swarm mode container shutsdown

### ISSUE THREAD

**Issue by vetional** [gettyimages/docker-spark#12]
I have a functional swarm using docker 1.12.1 but when I execute :

docker service create --name spark-master  gettyimages/spark /usr/spark-2.0.0/sbin/start-master.sh

The container keeps exiting after the start-master.sh completes. How can I keep the container running in a graceful manner?

**Comment by dylanmei** [comment]
Give this a try: `bin/spark-class org.apache.spark.deploy.master.Master -h master`
You can see it used in the provided [docker-compose](https://github.com/gettyimages/docker-spark/blob/master/docker-compose.yml#L3)

**Comment by vetional** [comment]
I tried that too earlier but it still kept shutting down the service.

So what I ended up doing is creating a dummy script which invokes the spark start-master.sh followed by a never ending while loop (as done by amplab for spark 1.0.0). But according to a few posts on SO this approach is not graceful during termination. 

```
#!/usr/bin/env bash

/usr/spark-2.0.0/sbin/start-master.sh 
while [ 1 ];
do
    tail -f /opt/spark-${SPARK_VERSION}/logs/*.out
        sleep 1
done
```

I was wondering if you have any remarks/suggestions on this.

**Comment by dylanmei** [comment]
`start-master.sh` daemonizes spark, so if you are going to use it that way then tailing something is a way to keep the container running.

I'd be interested getting more information on what kind of output you got with `bin/spark-class org.apache.spark.deploy.master.Master -h master` before it fell over.

**Comment by vetional** [comment]
To create the service I used the following command:
`docker service create --name spark-master-test --constraint 'node.hostname==master' -p 8082:8080  gettyimages/spark /usr/spark-2.0.0/bin/spark-class org.apache.spark.deploy.master.Master -h master`

Here is the output for docker service ps

```
ID                         NAME                     IMAGE              NODE    DESIRED STATE  CURRENT STATE          ERROR
4hb73q8p9hhqxwz3j710opaz3  spark-master-test.1      gettyimages/spark  master  Running        Running 1 seconds ago
8d8j9w2nwmxeed3m0s3dpsn0b   \_ spark-master-test.1  gettyimages/spark  master  Shutdown       Failed 7 seconds ago   "task: non-zero exit (1)"
afxgbumoe6ex7ymliw2kk70gk   \_ spark-master-test.1  gettyimages/spark  master  Shutdown       Failed 15 seconds ago  "task: non-zero exit (1)"
42kq9kczyylglncrh0mgrn5j9   \_ spark-master-test.1  gettyimages/spark  master  Shutdown       Failed 23 seconds ago  "task: non-zero exit (1)"
cpdd8lvuyv0yyh6ucbaq6aa6r   \_ spark-master-test.1  gettyimages/spark  master  Shutdown       Failed 31 seconds ago  "task: non-zero exit (1)"

```

**Comment by dylanmei** [comment]
Ah forgive me, `-h master` would fail if your host isn't actually resolvable as `master`. The error hidden in the logs is probably something like `Unresolved address`.

I imagine you can simply omit the `-h master` argument and get passed that.

The complete help text of running a master directly is easy to fetch: try this locally: `docker run --rm -t gettyimages/spark:2.0.0-hadoop-2.7 bin/spark-class org.apache.spark.deploy.master.Master --help`

It should output something like:

```
Usage: Master [options]

Options:
  -i HOST, --ip HOST     Hostname to listen on (deprecated, please use --host or -h) 
  -h HOST, --host HOST   Hostname to listen on
  -p PORT, --port PORT   Port to listen on (default: 7077)
  --webui-port PORT      Port for web UI (default: 8080)
  --properties-file FILE Path to a custom Spark properties file.
                         Default is conf/spark-defaults.conf.
```

**Comment by vetional** [comment]
That works! Thanks

**Comment by vetional** [comment]
Can you point me to some resource which explains the difference between the way it is running now and the while loop hack I used earlier?

**Comment by dylanmei** [comment]
When you ran the `spark-class ... --help`, you probably saw in the output that Spark began trapping signals:

```
INFO util.SignalUtils: Registered signal handler for TERM
INFO util.SignalUtils: Registered signal handler for HUP
INFO util.SignalUtils: Registered signal handler for INT
```

When the container stops, Spark as the foreground process will intercept the signal, and have a chance to quit gracefully. Using the other way, Spark is not the foreground process, rather `tail` is and so what you're quitting is `tail`, not Spark. Here's a decent article about this topic: https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86#.ajhmq0me3

**Comment by vetional** [comment]
Thanks, although now that I remember during my search for an answer I did come across  [this](http://stackoverflow.com/questions/36469386/docker-stop-spark-container-from-exiting) article which talks about the issue but I wasn't able to connect the dots or get to a proper article to understand the issue. Your answer and the medium post clarified my doubts. 

Thanks again for clearing this up.
