### ISSUE TITLE
/usr/spark-1.6.2 belongs to... nobody

### ISSUE THREAD

**Issue by laugimethods** [gettyimages/docker-spark#13]
When those Containers (`gettyimages/spark:1.6.2-hadoop-2.6`) are used (as a Slave) on a [Apcera Platform](https://www.apcera.com/), the following exceptions are raised:

```
[system-error] Process 'app' failed with status "exited(1)"
[stderr] 16/08/31 20:35:20 ERROR worker.Worker: Failed to create work directory /usr/spark-1.6.2/work
```

Indeed, the owner of `spark-1.6.2` is... `nobody`: 

```
root@ip-169-254-0-25:/# cd usr
root@ip-169-254-0-25:/usr# ls
bin  games  hadoop-2.6.3  include  java  jdk1.8.0_92  lib  local  sbin  share  spark-1.6.2  src
root@ip-169-254-0-25:/usr# ls -al
total 52
drwxr-xr-x 23 root   root    4096 Aug 26 23:31 .
drwxr-xr-x 41 root   root    4096 Aug 26 23:25 ..
drwxr-xr-x  2 root   root    4096 Aug 26 22:27 bin
drwxr-xr-x  2 root   root    4096 Aug 26 22:27 games
drwxr-xr-x  9  10021   10021 4096 Aug 26 22:27 hadoop-2.6.3
drwxr-xr-x  2 root   root    4096 Aug 26 22:27 include
lrwxrwxrwx  1 root   root      16 Aug 26 22:27 java -> /usr/jdk1.8.0_92
drwxr-xr-x  7 uucp       143 4096 Aug 26 22:28 jdk1.8.0_92
drwxr-xr-x 29 root   root    4096 Aug 26 23:18 lib
drwxrwsr-x 13 root   staff   4096 Aug 26 22:27 local
drwxr-xr-x  2 root   root    4096 Aug 26 22:27 sbin
drwxr-xr-x 62 root   root    4096 Aug 26 22:27 share
drwxr-xr-x 12 nobody nogroup 4096 Aug 26 22:28 spark-1.6.2
drwxr-xr-x  2 root   root    4096 Aug 26 22:28 src
```

Looks like Docker is natively able to get around that ownership, but not some other platforms... Therefore a `chown` would be useful.
Alternative (?): create in advance the /usr/spark-1.6.2/work/ directory under the root ownership.

**Comment by laugimethods** [comment]
FYI, the (temporary) [logimethods/docker-spark-gettyimages](https://hub.docker.com/r/logimethods/docker-spark-gettyimages/~/dockerfile/) Docker Image does solve that issue:

```
FROM gettyimages/spark:1.6.2-hadoop-2.6
RUN chown root ${SPARK_HOME}
```

**Comment by dylanmei** [comment]
Thanks for reporting this. I agree it's an issue.

I'm unsure how to repro the error exactly. Both `bin/spark-shell --conf spark.local.dir=/usr/spark-1.6.2/work` and `bin/spark-shell --conf spark.local.dir=/tmp/work` do the right thing and creates the directory.

**Comment by laugimethods** [comment]
I'm pretty sure you cannot reproduce this using the "official" Docker platform.
It only occurs when that image is run by Apcera (which has a stronger security policy)... 

For me, Docker should not also allow the manipulation of the /usr/spark-1.6.2/work/ directory, but that's another story.

**Comment by dylanmei** [comment]
Try pulling [the new build](https://hub.docker.com/r/gettyimages/spark/builds/b6rgg8bhlxpvfz2zo4iufsm) of the `1.6.2-hadoop-2.6` image. Please let me know how it goes on Apcera.

**Comment by laugimethods** [comment]
Looks like this new build solved this issue on Apcera!
Thank you very much.

**Comment by laugimethods** [comment]
Btw, I'm using your docker-spark images on the [docker-nats-connector-spark](https://github.com/Logimethods/docker-nats-connector-spark) project.

**Comment by dylanmei** [comment]
Awesome! Thanks for sharing. The Gatling pipeline idea is very cool.

**Comment by dylanmei** [comment]
I've also updated `2.0.0-hadoop-2.7` and `latest`.
