### ISSUE TITLE
spark-submit not working ?

### ISSUE THREAD

**Issue by soufiane-fadil** [gettyimages/docker-spark#16]
Dear all,
i've tried to use spark-submit and this what i get :

```
docker: Error response from daemon: Mounts denied: espaces for more info.
.
ions/XAMPP/htdocs/spark-processing/count.py
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#nam.
```

i've tried to Add my dir to docker and it works only if use `bin/run-example` always not for `bin/spark-submit`: 
```
docker run --rm -it -p 4040:4040 gettyimages/spark bin/run-example SparkPi 10
```

Any solution for this ?

**Comment by jacopofar** [comment]
@bloodymind which version od Docker? On which operating system (it seems OS X)?

It seems that you are sending a file which is not mounted for the Docker container, on my computer (Mac OS with Docker 1.13 beta using Docker tools) that command works so I suspect it's an issue of osxfs.

**Comment by soufiane-fadil** [comment]
@jacopofar ,

Sorry for the delay i received the email as a spam!

Yeah i'm using Docker version 1.12.5 on OS X El Capitan. it could be that :/
