### ISSUE TITLE
Q: Why do you add extra jars to spark lib dir?

### ISSUE THREAD

**Issue by l15k4** [gettyimages/docker-spark#4]
Hey,

you are adding deps to spark lib directory but they will be still missing in the driver, right?

So to be able to use `hadoop-aws` one still needs to do : 

```
spark-submit --jars=file:/usr/spark-1.5.1-bin-hadoop2.6/lib/aws-java-sdk-1.7.14.jar,file:/usr/spark-1.5.1-bin-hadoop2.6/lib/hadoop-aws-2.6.0.jar,file:/usr/spark-1.5.1-bin-hadoop2.6/lib/google-collections-1.0.jar,file:/usr/spark-1.5.1-bin-hadoop2.6/lib/joda-time-2.8.2.jar
```

I'm wondering, aren't they then doubled on the classpath? Because `spark-submit --jars` would add them on classpath of executors as well, so I'm curious how do you use it.

**Comment by dylanmei** [comment]
When using the docker image for drivers and also executors, it's not necessary to provide them with `--jars`. Do you have a different approach?

**Comment by l15k4** [comment]
Well I had to use `--jars` or  `--packages` to be able to use `hadoop-aws` otherwise it failed on ClassNotFound exception of those classes from `hadoop-aws` jar. But I was calling `spark-submit` via apache Zeppelin (but I wasn't using the built-in spark)... So maybe it's caused by that...

I'm not quite sure that adding deps to `spark_home/lib` is a good practice for both executor and driver side...

**Comment by dylanmei** [comment]
You are absolutely right. I think it will seem to work with `--master local[*]` but not if the work is distributed. Thanks, I'll consider getting rid of the jars, or moving them out of `$SPARK_HOME/lib` and ensuring they'll work out of the box.

**Comment by dylanmei** [comment]
Going forward (spark 1.6.1+) these extra jars have been removed.

**Comment by l15k4** [comment]
Hey,

I thought that the correct approach would be download them to a different directory say `extra` and then supply them through `--jars=file:/` flag... That way they would be added on classpath for driver and executor... Now you got rid of them entirely so it is user's responsibility to load them, right ?

The problem that I was pointing at was that you put them into `$SPARK_HOME/lib` where they were implicitly added on the executor classpath and in order to add them on Driver's classpath you had to add them through `--jars` flag, which is OK for Driver but it is added twice on the executor's classpath because executor gets everything from `$SPARK_HOME/lib` on classpath implicitly ...

**Comment by dylanmei** [comment]
Hadoop/S3 should be working out of the box now. Is there something else you feel should be added by default?

**Comment by l15k4** [comment]
> Hadoop/S3 should be working out of the box now.

Do you mean `spark-cloud` ? https://github.com/steveloughran/spark/blob/d55fbe6c907b8415cc2516bd7ef62c7da509d323/cloud/pom.xml

Well, to find a common ground : 
- Master needs `spark-core`
- Workers/Executors need `spark-cloud` + `hadoop` (+ everything that Driver is using in tasks)
- Driver needs `spark-core` + optionally `hadoop` + dependencies that it uses itself

I think that Spark docker image for `Master` and `Workers/Executors` should contain `spark-cloud` + `hadoop` and `Driver` application should include everything else via `spark.jars`.

The question is : where should `hadoop-aws` be? It has a lot of transitive dependencies (hadoop, jackson, aws-java-sdk, etc.) and if you include it to your client application it gets quite huge and it brings a lot of conflicts after it gets put on the Worker's classpath... Without using the `spark-cloud` dependency you don't get `hadoop-aws` as a Spark's transitive dependency

**Comment by dylanmei** [comment]
I did nothing to install `hadoop-aws` it is already available with hadoop-2.6. Your issue began with hadoop-2.4 when `hadoop-aws` and friends did not come for free.

So if you have a look around, you'll see where the dependencies are.

```
% docker run --rm -it --name spark gettyimages/spark:1.6.1-hadoop-2.6 bash
root:/usr/spark-1.6.1#  ls $HADOOP_HOME/share/hadoop/tools/lib/ | grep aws
aws-java-sdk-1.7.4.jar
hadoop-aws-2.6.3.jar
```

I'm not familiar with spark-cloud. It doesn't seem mainstream yet.

**Comment by l15k4** [comment]
I see, I didn't know it comes with hadoop distro, it isn't part of spark distribution though : 

```
$ ./dev/make-distribution.sh --name custom-spark --tgz -Phadoop-2.7 -Dhadoop.version=2.7.2 -Dscala-2.11
$ tar xvf spark-2.0.0-preview-bin-custom-spark.tgz
$ ls spark-2.0.0-preview-bin-custom-spark/jars | grep hadoop
avro-mapred-1.7.7-hadoop2.jar
hadoop-annotations-2.7.2.jar
hadoop-auth-2.7.2.jar
hadoop-client-2.7.2.jar
hadoop-common-2.7.2.jar
hadoop-hdfs-2.7.2.jar
hadoop-mapreduce-client-app-2.7.2.jar
hadoop-mapreduce-client-common-2.7.2.jar
hadoop-mapreduce-client-core-2.7.2.jar
hadoop-mapreduce-client-jobclient-2.7.2.jar
hadoop-mapreduce-client-shuffle-2.7.2.jar
hadoop-yarn-api-2.7.2.jar
hadoop-yarn-client-2.7.2.jar
hadoop-yarn-common-2.7.2.jar
hadoop-yarn-server-common-2.7.2.jar
parquet-hadoop-1.7.0.jar
```

I'm considering using hadoop that comes with spark distribution to spare myself of possible problems with the hadoop distribution provided ...

**Comment by dylanmei** [comment]
Right, here we are installing hadoop side-by-side with the "user-provided hadoop" flavor of Spark. One we set `$HADOOP_HOME`,  Spark will always use that.

We're on hadoop-2.6 here, but check it out: `hadoop-2.7.2` comes with aws _and_ azure libraries...

```
% curl -sL "http://archive.apache.org/dist/hadoop/common/hadoop-2.7.2/hadoop-2.7.2.tar.gz" -o hadoop.tar.gz
% tar tvf hadoop.tar.gz | grep -E "(aws|azure).+.jar"
-rw-r--r-- jenkins/jenkins  102998 2016-01-25 16:20 hadoop-2.7.2/share/hadoop/tools/lib/hadoop-aws-2.7.2.jar
-rw-r--r-- jenkins/jenkins  662947 2016-01-25 16:20 hadoop-2.7.2/share/hadoop/tools/lib/azure-storage-2.0.0.jar
-rw-r--r-- jenkins/jenkins 11948376 2016-01-25 16:20 hadoop-2.7.2/share/hadoop/tools/lib/aws-java-sdk-1.7.4.jar
-rw-r--r-- jenkins/jenkins   134231 2016-01-25 16:20 hadoop-2.7.2/share/hadoop/tools/lib/hadoop-azure-2.7.2.jar
```

**Comment by l15k4** [comment]
An interesting question is whether to distribute "client/driver" applications in this docker image too. Because even though it is just a basic spark hello-world app, you need a dependency on `spark-core`, possibly even hadoop and aws-java-sdk, which are quite heavy deps and it is already part of the docker image. So one could also use it like this : 

```
docker run gettyimages/spark java -cp '/opt/my-spark-app.jar:$SPARK_HOME/jars/*' com.example.App
```

and have your application have : 

```
"org.apache.spark" %% "spark-core" % "1.6.0" % "provided"
```
