### ISSUE TITLE
docker-compose up fails with "client version 1.21 is too old"

### ISSUE THREAD

**Issue by dkmiller** [gettyimages/docker-spark#48]
When I clone the repository and run `docker-compose up` from the root, I get:

> ERROR: client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version

The output of `docker-compose --version`:

> docker-compose version 1.23.2, build 1110ad01

The output of `docker --version`:

> Docker version 18.09.0, build 4d60db4

I've made a fix locally following [this GitHub issue](https://github.com/docker/compose/issues/5103), which I'll submit as a pull request.

**Comment by bryceageno** [comment]
ok, I'm in the office today so i'll get it merged and fixed, thanks.
