### ISSUE TITLE
master/worker unable to start/kill.

### ISSUE THREAD

**Issue by oche191** [gettyimages/docker-spark#6]
Hi guys, thank you for this image. Idea and simplicity are great. 
But, i am experiencing strange problems with this image. I am running it within the `docker-compose` and behaviour of master/worker containers is very unpredictable. e.g. Only master is stared, without worker. But, observing through `docker ps` shows that there are both containers running. `docker kill "id"` is able only to kill a master, but within the worker it just hangs.

I have this behaviour with docker 1.9.1 and OS X 10.11.3 El Capitan also i've reproduced it on Ubuntu 14.04.

Do you have any idea what it could be ?

Thanks,
Alex

**Comment by dylanmei** [comment]
I have a peer that has seen similar behavior on Docker 1.9.1 also. But I'm on 1.9.1 and don't see the problem. For my peer, going back to 1.9.0 solved his problem. We did this by creating a new machine, specifying the boot2docker image to use.

```
docker-machine create --driver virtualbox --virtualbox-cpu-count -1 --virtualbox-disk-size 32768 --virtualbox-memory 2048 --virtualbox-boot2docker-url=https://github.com/boot2docker/boot2docker/releases/download/v1.9.0/boot2docker.iso default
```

That's not what you wanted to hear I am sure. Meanwhile, I'll rebuild :latest at hub.docker.com.

**Comment by oche191** [comment]
Thank you Dylan!
This really works without any troubles.

**Comment by dylanmei** [comment]
I'm glad to hear it. Docker 1.10 [was just released today](http://blog.docker.com/2016/02/docker-1-10). I'll keep this issue open until I test it there.

**Comment by leninmehedy** [comment]
same issue here. cannot stop or kill worker with Docker 1.9. I am going to download Docker 1.10 and give it a try.

and it worked after updating to Docker 1.10!! 
thank you Dylan!

**Comment by dylanmei** [comment]
Good news! Thanks @leninmehedy
