### ISSUE TITLE
4040 sparkui not running

### ISSUE THREAD

**Issue by geoHeil** [gettyimages/docker-spark#8]
Hi,
where can I find the defaults spark UI which gives a great overview of the jobs? Neither on master nor on worker seems to be something running at `4040`.

**Comment by dylanmei** [comment]
Assuming you're using the included docker-compose:
- master ui port = 8080
- worker ui port = 8081
- application ui port = 4040

If you're not using docker-compose, try this:

```
> docker run --rm -it -p 4040:4040 gettyimages/spark bin/spark-shell
> open http://$DOCKER_IP:4040
```

**Comment by dylanmei** [comment]
Commit 423a4c9603fb6d7421b4b752e15afffb3dd69665 adds  `-p 4040:4040`  to the `docker run` examples in the readme. I'd like to know if that clears things up.

**Comment by geoHeil** [comment]
Great. I will try your ideas and see if that helps. Meanwhile one more question regarding your docker-compose file and Docker Toolbox / boot2docker vm:

http://stackoverflow.com/questions/36140734/docker-toolbox-networking-problems
I can see the links in the master UI but they all point to the internal links of the containers which are not available on osx. 
As you can see from the link I already tried port-forwarding but this does not help with the name resolution problems.

**Comment by dylanmei** [comment]
I don't have a direct solution to offer. 

AFAIK Spark doesn't make it possible to assign an advertise address to master/workers.

On OSX in /etc/hosts I assign my docker host ip to docker.local. When I click on such a link I just edit the ip in the address baI to docker.local. 

The truth is I spend little time locally either running Spark jobs or with spark-shell. For ad hoc Spark I use Zeppelin in a Mesos cluster. For a packaged Spark job I use docker-compose just enough to make sure the jar I built is run able, metrics and logs are well formed from the perspective of the driver and the executors. Then I take my jar to the cluster and tune it there -- or find it won't run and come back to square one. 

Two things I can recommend outside of moving to Linux: 
- run a docker-machine with a cloud provider such as aws, open stack, etc. If you have such an account, docker-machine makes it easy. 
- experiment with OSXs native hyper visor: https://github.com/zchee/docker-machine-driver-xhyve

**Comment by geoHeil** [comment]
Thank you for your input.

Regarding 1) the UI:
- Indeed, I run your docker-compose file
- In single-node mode e.g. `master=local[*]` port `4040` serves the application UI e.g. as you suggested `docker run --rm -it -p 4040:4040 gettyimages/spark bin/run-example SparkPi 10`
- When run in distributed mode (e.g. a single worker, single master) `8080` and `8081` correctly serve the master and slave UI's. However`$DOCKER_HOST:4040`does not serve the application UI.
- Strangely it is  opposite for port `7077`. This one only works in the distributed setup e.g. only there It is possible to connect from pyspark / sparkR. In the local setup, nothing seems to listen on this port.

Regarding 2) the host name resolution:
-  I do not understand why xhyve would circumvent this problem (even though it is pretty cool)
-  According to https://thepracticalsysadmin.com/xhyve-vs-vbox-driver-benchmarks-for-docker-machine/  xhyve seems to be as fast as virtualbox
- thanks for the insight regarding Zeppelin. I will try to add that.

**Comment by aleury** [comment]
According to http://spark.apache.org/docs/latest/spark-standalone.html you can set the `SPARK_PUBLIC_DNS` environment variable. For example, using Docker for Mac, I set this environment variable in `docker-compose.yml` to localhost and am able to navigate between the master and worker UIs without rewriting the URIs.

**Comment by EncodePanda** [comment]
I've created a PR adding `SPARK_PUBLIC_DNS` env --> https://github.com/gettyimages/docker-spark/pull/10

**Comment by dylanmei** [comment]
Thanks @rabbitonweb -- this should be addressed assuming latest docker setups (Docker on Mac, Docker on Windows).

**Comment by EncodePanda** [comment]
This PR was merged, I think we can close this issue

**Comment by toddpi314** [comment]
@aleury Somebody buy this man a beer.
